config/routes.rb
Rails.application.routes.draw do
  #devise_for :views
  devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations'} #, sessions: 'engineers/sessions'}

#   devise_scope :engineers do
#     get 'login', to: 'devise/sessions#new'
#   end
#  devise_scope :engineers do
#     get 'logout', to: 'devise/sessions#destroy'
#   end
#  devise_scope :engineer do
#     get 'home', to: 'devise/sessions#index'
#   end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


#  devise_for :engineers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   
#       devise_scope :engineer do
#    get 'signup', to: 'devise/registrations#new'
# end
  


#get "home#index"
  #devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations'} #, sessions: 'engineers/sessions'}
#    , sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

 #resources :engineers
 #resources :engineers do
#   resources :recording_sessions 
# end


 #root 'recording_sessions#index'
 
  # resources :recording_sessions, :artists, :studios

    # resources :engineers do
    # resources :recording_sessions # , only: :create
    #  end
#    resources :artists do
  #  resources :recording_sessions # , only: :create
 #    end
 #   resources :studios do
 #   resources :recording_sessions # , only: :create
 #   end















end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/engineer.rb
class Engineer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
 devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :validatable
         # devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:github]



  def self.from_omniauth(auth)
    binding.pry
    where(provider: auth.provider, uid: auth.uid).first_or_create do |engineer|
      engineer.provider = auth.provider
      engineer.name = auth.info.name
      engineer.uid = auth.uid
      engineer.email = auth.info.email
      engineer.password = Devise.friendly_token[0, 20]
    end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

#  def destroy
# #    session[:engineer_id] = nil
#  session[:current_user_id] = user.id
# sign_out @engineer 
# redirect_to root_url, notice: "Logged out!"
#   end

def destroy
    Engineer.find(params[:id]).destroy
    redirect_to action: 'index'
    #redirect_to Engineer_path
  end



end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @engineer = Engineer.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @engineer
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
before_action :authenticate_engineer!
    private
    def signup_params
        params.require(:engineer).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation)
    end

    # def signin_params
    #     params.require(:engineer).permit( :name,
    #                                   :email,
    #                                   :password,
    #                                   :password_confirmation)
    # end

    def account_update_params
        params.require(:engineer).permit( :name,
                                        :email,
                                        :password,
                                        :password_confirmation,
                                        :current_password)
    end



#  def index
#     @engineers = Engineer.all
#     #@engineer = Engineer.find(params[:id])
#     @engineer = current_engineer #Engineer.find(params[:id])
#     @recording_sessions = RecordingSession.all
#     @studios = Studio.all
#     @artists = Artist.all
#        redirect_to '/recording_sessions'
#  end



# def show
#      index
# #     # binding.pry
#      @engineer = Engineer.find(params[:id])
#      redirect_to action: 'index'
    
#    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/engineers/new.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/layouts/_messages.html.erb
<p class="navbar-text pull-right">
  <% if engineer_signed_in? %>
  Logged in as <strong><%= current_engineer.name %></strong>. <br>

  <%= link_to 'Edit profile', edit_engineer_registration_path, :class => 'navbar-link' %> | <br>
  <%= link_to 'View Recording Sessions', recording_sessions_path, :class => 'navbar-link' %> | <br>
  <%= link_to "Logout", destroy_engineer_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_engineer_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_engineer_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

  <body>
  
  
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studio Session Scheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


        <%= render 'layouts/messages' %>
        <!-- Last -->
  <body>
    <%= yield %>
  </body>
</html>